- name: "feature"
  color: "0E8A16"
  description: "New feature to implement"
  
- name: "bug"
  color: "D73A4A"
  description: "Something isn't working as expected"
  
- name: "documentation"
  color: "0075CA"
  description: "Improvements or additions to documentation"
  
- name: "architecture"
  color: "6F42C1"
  description: "Structural and design changes" 